#pragma once

#define FLAG_EMBEDPRESENT 1
#define FLAG_EMBEDENCRYPT 2
#define FLAG_ELEVATE 4

#define ERR_UNKOWNFILEERROR 1001
#define ERR_NOTENOUGHDATA 1002
#define ERR_ASSERTIONERROR 1003
#define ERR_MALLOCERROR 1004
#define ERR_UNSUFFICIENTPRIVILEGES 1005
#define ERR_INTERNALHASHERPROBLEM 1005
#define ERR_ITEMHASHDONTMATCH 1005
#define ERR_WINAPIERROR 1006